spring.application.name=poetry
server.port=8866

#spring.elasticsearch.uris=http://119.29.133.12:92
#spring.elasticsearch.username=elastic
#spring.elasticsearch.password=your_password
spring.elasticsearch.uris=http://localhost:9200

# ??????????
logging.charset.console=UTF-8
# ???????????
logging.charset.file=UTF-8
# ??????????????????
logging.file.name=logs/poetry.log
