### 获取当前天气-默认（深圳）
GET http://{{server_port}}/api/weather/current

### 获取当前天气-按坐标（永寿）
GET http://{{server_port}}/api/weather/current?lat=34.6833&lon=108.1500

### 获取当前天气-按坐标（深圳）
GET http://{{server_port}}/api/weather/current?lat=22.5431&lon=114.0579

### 获取当前天气-按坐标（上海）
GET http://{{server_port}}/api/weather/current?lat=31.2304&lon=121.4737

### 获取当前天气-按城市名
GET http://{{server_port}}/api/weather/current?city=上海

### 获取天气预报-按坐标（北京）
GET http://{{server_port}}/api/weather/forecast?lat=39.9042&lon=116.4074

### 获取天气预报-按城市名
GET http://{{server_port}}/api/weather/forecast?city=北京

### 获取当前天气-按城市名
GET http://{{server_port}}/api/weather/current?city=深圳
